twig_component:
    # anonymous_template_directory: 'components/'
    anonymous_template_directory: 'components/cva'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
